# Generated by Django 3.1.7 on 2021-03-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=30)),
                ('product_image', models.ImageField(upload_to='')),
                ('product_name', models.TextField(max_length=30)),
                ('product_description', models.TextField(max_length=30)),
                ('timeline_from_date', models.DateField(default=None)),
                ('timeline_to_date', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.TextField(max_length=30, unique=True)),
                ('password', models.TextField(max_length=20)),
            ],
        ),
    ]
